### ISSUE TITLE
[Windows] Opus unavailable

### ISSUE THREAD

**Issue by tor255** [meew0/discordrb#407] opened 2017-09-09 11:10 UTC
(Windows 10 32-bit, ruby 2.4.1)

I've done everything the tutorial said to do in regard to dependencies, I have libopus-0.dll renamed to opus.dll in my bot's directory, and in my path. and yet I keep getting this error:
`Exception: #<LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>`

and when I try to manually `require 'opus-ruby'` it raises a LoadError, saying: 
`LoadError: Could not open library 'opus': The specified module could not be found.`
`.`
`Could not open library 'opus.dll': The specified module could not be found.`

please help

**Comment by unleashy** [comment] 2017-09-09 15:07
Did you add a directory to the PATH (e.g. "C:/dank_c_libs") and not the path to the `opus.dll` (e.g. "C:/dank_c_libs/opus.dll")? It won't work if you put a file and not a directory in the PATH.

Also, try this in some random ruby file and see if it still fails to load:

```ruby
require 'ffi'

module Opus
  extend FFI::Library

  ffi_lib '<absolute path to opus library goes here>'
end
```

**Comment by tor255** [comment] 2017-09-10 03:47
I tried your code, and it worked fine.

The path to my `opus.dll` is "C:\programming\opusfile", and that is exactly what is in my PATH environmental variable.

**Comment by unleashy** [comment] 2017-09-10 04:01
Well, that's weird. I'm afraid I have no idea what's going on. Sorry.

You could try altering the opus-ruby files that are in your computer and change the ffi_lib call to a direct path to your DLL. Maybe that does it. The file should be in `<ruby install path>\lib\ruby\gems\<ruby version>\gems\opus-ruby-1.0.1\lib\opus-ruby.rb`.

**Comment by tor255** [comment] 2017-09-10 04:06
My computer is a bit like that.

Alright, thanks for the help, I'll just change opus-ruby.

**Comment by z64** [comment] 2017-09-10 04:11
If that works for you, do let us know! This seems to come up rather often as the existing instructions appear to be hit or miss with people, and most of us who work on `discordrb` have been unable to reproduce (or fix it if we could!).

Questions as issues are fine - this is a good one per my above statement - but also consider joining us on the [Discord API server](https://discord.gg/0SBTUU1wZTWfFQL2) where we can work with you to more quickly troubleshoot things and answer any questions you have :smiley:

**Comment by tor255** [comment] 2017-09-10 05:14
I finally fixed it! But now my audio is really laggy lol.

Anyway, I changed line 9 in `opus-ruby.rb` from:

`ffi_lib 'opus'`

to:

`ffi_lib "C:\programming\opusfile\opus.dll"`

ALSO, the ffi_lib path cannot contain forward slashes, or else it doesn't work.

**Comment by unleashy** [comment] 2017-09-10 15:59
>ALSO, the ffi_lib path cannot contain forward slashes, or else it doesn't
work.

got damn windows smh

2017-09-10 2:14 GMT-03:00 tor255 <notifications@github.com>:

**Comment by z64** [comment] 2017-10-26 20:32
Just wanted to make a note here to anyone reading this issue -

If any of the steps in this issue worked for you in getting voice on Windows to work where our existing instructions (readme, wiki) didn't, please feel free to offer suggestions / a PR so we can get this information in a place where people are more likely to find it.

I'm unfamiliar with voice on Windows and don't know what the root cause of the difficulties could be between any two users experiencing difficulties to make an informed commit myself :)

**Comment by SPQRBrutus** [comment] 2017-12-27 00:22
Hello,

I have same issuse but on linux (Ubuntu 16.04). Any help ?

Thanks

**Comment by z64** [comment] 2017-12-28 05:26
Hi @SPQRBrutus!

It really should have been marked as such, but this thread is really for tracking windows-related pathing issues some users have been having that we haven't been able to reproduce reliably. 

There are no known issues with voice dependencies on linux OS at this time.
In any case, please ensure you have followed our installation instructions for voice dependencies from our wiki:
- [libopus](https://github.com/meew0/discordrb/wiki/Installing-libopus)
- [libsodium](https://github.com/meew0/discordrb/wiki/Installing-libsodium#linux)

If you have further problems, please open a new issue or [join us on discord](https://discord.gg/cyK3Hjm).

**Comment by c-stella** [comment] 2018-03-14 00:50
Hi.

I know it's old post, but maybe I found solution.
I was able to solve using opus version 0.7.
With newest version(0.9) it seems that a problem arises somewhat.

I hope this may help someone.

**Comment by z64** [comment] 2018-06-19 04:48
Closing this as a stale issue / nothing actionable has come out of this. I would like to see some wiki update, but not if we can't pinpoint the issue into something reproducible. And on the bright side, this particular issue actually has hardly come up at all lately (:smile:)

**Closed by z64** 2018-06-19 04:48 UTC
Labels: question, voice, windows
