### ISSUE TITLE
Lots of NoMethodErrors since yesterday

### ISSUE THREAD

**Issue by i-hardy** [meew0/discordrb#500] opened 2018-05-19 16:14 UTC
I have [a bot](https://github.com/i-hardy/woolf) using this gem that's running on about 150 servers, and since the version on rubygems is over a year out of date I've been pulling the gem directly from the master branch here. Today after the daily reboot of the bot I've started seeing an insane amount of NoMethodErrors in the bot's logs:

<img width="1169" alt="screen shot 2018-05-19 at 17 02 45" src="https://user-images.githubusercontent.com/29146931/40270531-050cae6e-5b87-11e8-9a44-2a4a8e40b4cc.png">

<img width="1165" alt="screen shot 2018-05-19 at 17 07 09" src="https://user-images.githubusercontent.com/29146931/40270541-1f3973c6-5b87-11e8-8ce6-0e35bbf07c02.png">

I haven't made any changes to the bot's code in several weeks, and I don't know why `update_voice_state` would be getting called at all, since the bot has no voice functionality. Any ideas?

**Comment by z64** [comment] 2018-05-20 05:13
Hi @i-hardy !

I've taken some time to look into these backtraces.

---

First about `add_member`

The line in that commit is the following:

```rb
   4     # Adds a member to the member cache.
   3     # @note For internal use only
   2     # @!visibility private
   1     def add_member(member)
3058       @member_count += 1
   1       @members[member.id] = member
   2     end
```
This would mean that `@member_count` is `nil`, meaning when the server was cached from Discord, this field was missing. This is simply read from the `GUILD_CREATE` payload in `Server#initialize(data)` as:
```rb
2745       @member_count = data['member_count']
```
That said, I'm unfamiliar when at all this would be missing from Discord's end.
---

Looking at `update_voice_state`

This is the following line:

```rb
  10     # Internal handler for VOICE_STATE_UPDATE
   9     def update_voice_state(data)
   8       @session_id = data['session_id']
   7
   6       server_id = data['guild_id'].to_i
   5       server = server(server_id)
   4       return unless server
   3
   2       user_id = data['user_id'].to_i
   1       old_voice_state = server.voice_states[user_id]
674        old_channel_id = old_voice_state.voice_channel.id if old_voice_state
   1
   2       server.update_voice_state(data)
   3
   4       old_channel_id
   5     end
```

I'll note here that yes, even though your bot might not use *voice sending* functions, Discord still sends us `VOICE_STATE_UPDATE` events that lets you know when other users connect to voice channels. We handle this event and cache data to provide you with abstractions for figuring out what voice channel a user is in, or figuring out who is in a particular voice channel. This is totally independent of any voice sending/receiving features.

To understand this error, I'll have to explain a little how the flow of data from Discord goes after connecting. After you authenticate, you get a stream of `GUILD_CREATE` events which are server objects with several additional fields than normal in order to allow bots to seed their cache of data - one of these extra fields is `voice_states` representing all of the users who are connected to voice in that server at the time of your bot logging in. 

A voice state looks like this:
```json
{
    "channel_id": "157733188964188161",
    "user_id": "80351110224678912",
    "session_id": "90326bd25d71d39b9ef95b299e3872ff",
    "deaf": false,
    "mute": false,
    "self_deaf": false,
    "self_mute": true,
    "suppress": false
}
```
This means that we somehow received something like this as part of `GUILD_CREATE`:
```json
"voice_states": [
  {
    "channel_id": null,
  }
]
```
Which would cause a follow-up `VOICE_STATE_UPDATE` to fail with the exception in your screenshot.

Again, I have no idea why this would occur. 

---

So, I'm sorry to say that this is totally strange and as far as I can see this is indicative that something was wrong with Discord, possibly related to the outages and issues over the past few days. It can be argued that we currently do not handle these nullable fields safely, so while this theoretically should *never* happen, it is technically a bug in that we don't handle the bad state Discord sent us well.

Is this still happening for you? If so, I could probably tell you more or would be able to at least reproduce this to better apply a "fix" for it. I have a hunch as to what kind of state might have done it, but just a straight up guess that will be very difficult to test. Otherwise this is going to be pretty low on the to-do list.

Any other questions, feel free to ask here or join us in Discord :slightly_smiling_face: 
(also yes sorry - we hope to have a release very soon!)

**Comment by z64** [comment] 2018-05-20 05:28
I was just thumbing through issues looking for something else, and came across this: #327

This has happened before, but on *extremely* rare occasion it seems, so we haven't had the information / motivation to do anything actionable about it.

**Comment by i-hardy** [comment] 2018-05-20 09:32
Thanks for the quick response! I pointed my Gemfile at commit 4a3f975846bd yesterday and haven't seen any recurrence of these errors since, but if it's down to problems on Discord's end as you suspect then that may not mean much. I _did_ get warnings about pretty much every server being 'unavailable due to an outage' just before the wall of stack traces began.

Completely understand if this is just a weird edge case that it's hard to replicate and handle effectively. I'll keep an eye out for it happening again to see if I can get any more useful information.

**Comment by z64** [comment] 2018-06-19 04:44
Going to close this one. While it is technically a "bug", the bug is that we don't handle bad state gracefully in a lot of places. This is something we're just going to hopefully improve on over time.  Maybe another, more focused issue can be open at another point when it makes sense to focus on those things.

There's nothing actionable to do here specific to this issue and the particular incident is unlikely to occur again. In any case, thanks for reporting and glad I could help shed some light on the problem! If it happens again feel free to reopen.

**Closed by z64** 2018-06-19 04:44 UTC
Labels: bug, question
