### ISSUE TITLE
Disconnect issues

### ISSUE THREAD

**Issue by cha55son** [meew0/discordrb#27] opened 2015-12-29 16:21 UTC
I'm getting a ton of disconnect errors. Link below. My bot will stay up for about a day then will consistently fail to connect with the servers. It may be a simple setting in discord itself, but I wasn't sure. Do you have any insight?

http://pastebin.com/raw/xFnFYQM9

I'm running on Centos 7 with node 0.12.7. Using foreverjs to manage the server and restart when it fails. Although this doesn't seem to help. The bot can't connect (~100 times) then restarts, forever then starts it again and the cycle continues until forever reaches its max attempts and kills the script completely.

**Comment by cha55son** [comment] 2015-12-29 16:24
Well it looks like i've got two bots running at the moment (not sure how that happened) Let me ensure I get the same issue with a single bot before anyone dives into this issue.

**Comment by cha55son** [comment] 2015-12-31 19:55
I've confirmed this is still happening with a single instance.

**Comment by meew0** [comment] 2015-12-31 21:52
This seems like a network problem; I'm running discordrb bots 24/7 and they're pretty stable. Are you sure this is not because of Discord connectivity issues?

**Comment by cha55son** [comment] 2015-12-31 22:19
Possibly, but i'm not sure what the issue would be. I can start the bot and it will typically stay up for a day or so then fail with the logs i've posted above.

**Comment by meew0** [comment] 2016-01-03 21:09
After some testing with long running bots I'm pretty confident that this is not a discordrb issue, as there are no errors in the logs and it seems like the connection has not been closed by discordrb. As a workaround I would suggest using a separate script to restart the bot script every day. If you find any evidence that this is actually caused by discordrb, please let me know.

**Closed** 2016-01-03 21:09 UTC
Labels: wontfix

**Comment by cha55son** [comment] 2016-01-03 21:21
To shed a little more light on the situation. I've stood up a hubot instance with hubot-discord and I'm seeing the same symptoms. Therefore it's either a network issue or something on discord's end. Thanks for entertaining this issue. If I find anything remotely related to this problem I'll let you know.
