### ISSUE TITLE
User tracking/caching? doesn't update for some voice-channels

### ISSUE THREAD

**Issue by Apexal** [meew0/discordrb#188] opened 2016-08-20 01:26 UTC
~~This works perfectly with the latest release (v2.1.3). This happens using the latest `master` branch:~~
This happens on the latest release but after a few hours, but it occurs every time I leave the bot running for a long time. It happens very very quickly with the GitHub version. 

There is one voice-channel on my server that is dynamically created by the bot and named **[New Room]**. When somebody joins/leaves/mutes/deafens in it the voice_state_update event works fine but `event.channel.users` (or finding the channel by name and calling `#users`) is always empty no matter how many people are connected.

**Comment by Apexal** [comment] 2016-08-20 01:46
It has something to do with `@server.voice_states`?

**Comment by Apexal** [comment] 2016-08-20 20:47
Just realized an issue I was having after running the bot for a long time using v2.1.3 is actually the same bug as this. Updated the issue.

**Comment by meew0** [comment] 2016-09-01 22:25
I can't reproduce this issue; on what timescales does it occur? Voice state tracking always works perfectly for me.

**Comment by meew0** [comment] 2016-09-23 22:26
I'm closing this for now - please reopen if you have more information.

**Closed** 2016-09-23 22:28 UTC
Labels: bug
