### ISSUE TITLE
Issue setting channel topic

### ISSUE THREAD

**Issue by Beat-Nick** [meew0/discordrb#241] opened 2016-10-05 15:31 UTC
I'm running into an issue when trying to set the channel topic. I have the command below loaded from a module.
```
command :topic do |event|
  binding.pry
  event.channel.topic="test"
end
```

In a pry session I run the event.channel.topic="test" and get the following error:

```
NoMethodError: undefined method `update_channel' for Discordrb::API:Module
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/discordrb-3.0.1/lib/discordrb/data.rb:1369:in `update_channel_data'
```

Taking a look at data.rb I see that it makes a call to` API::Channel.update(vars)` and it looks like it should all flow through correctly... I can't find what is calling the update_channel method, or where that method is stored. Any help would be appreciated.

**Comment by meew0** [comment] 2016-10-05 15:35
This is a duplicate of #238, which is fixed in master but not in any release. Use discordrb from master if you need this, or wait for the next release (should be soon)

**Closed** 2016-10-05 15:35 UTC
Labels: duplicate

**Comment by Beat-Nick** [comment] 2016-10-05 15:41
Ah, didn't realize master wasn't the latest release. Just wanted to make sure I wasn't going crazy. Thanks!
